CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    last_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    img_url VARCHAR(255),
    parent_id BIGINT,

    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    label VARCHAR(255) NOT NULL
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    prep_time INTEGER NOT NULL,
    servings INTEGER NOT NULL,
    publication_date DATE NOT NULL,
    img_url VARCHAR(255),

    category_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    CONSTRAINT fk_recipe_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_recipe_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE recipe_tags (
    recipe_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    PRIMARY KEY (recipe_id, tag_id),
    CONSTRAINT fk_rt_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id),
    CONSTRAINT fk_rt_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    amount DOUBLE PRECISION NOT NULL,
    unit VARCHAR(255) NOT NULL,

    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,

    CONSTRAINT fk_ri_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id),
    CONSTRAINT fk_ri_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (id)
);

CREATE TABLE steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    step_order INTEGER NOT NULL,
    instructions VARCHAR(5000) NOT NULL,
    img_url VARCHAR(255),
    recipe_id BIGINT NOT NULL,

    CONSTRAINT fk_step_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    rating INTEGER NOT NULL,
    comment VARCHAR(2000),
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,

    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_review_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id)
);

CREATE TABLE favourites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL,
    deleted_at TIMESTAMP,

    like_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,

    CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_fav_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id)
);

-- Unique slug for (active) recipes
CREATE UNIQUE INDEX idx_recipe_slug ON recipes (slug) WHERE deleted_at IS NULL;

-- Unique email for (active) users
CREATE UNIQUE INDEX idx_user_email ON users (email) WHERE deleted_at IS NULL;

-- Unique labels for (active) tags
CREATE UNIQUE INDEX idx_tag_label ON tags (label) WHERE deleted_at IS NULL;

-- Unique names for (active) ingredients
CREATE UNIQUE INDEX idx_ingredient_name ON ingredients (name) WHERE deleted_at IS NULL;

-- User can review single recipe only once
CREATE UNIQUE INDEX idx_review_user_recipe ON reviews (user_id, recipe_id) WHERE deleted_at IS NULL;

-- User can like recipe only once
CREATE UNIQUE INDEX idx_favourite_user_recipe ON favourites (user_id, recipe_id) WHERE deleted_at IS NULL;

-- Recipe can contain single ingredient only once (Usually hard constraint regardless of soft delete, but keeping consistent)
CREATE UNIQUE INDEX idx_recipe_ingredient_unique ON recipe_ingredients (recipe_id, ingredient_id);

-- Recipe can only contain one instruction step at one step_order
CREATE UNIQUE INDEX idx_recipe_step_unique ON steps (step_order, recipe_id);

-- Categories slug unique
CREATE UNIQUE INDEX idx_category_slug ON categories (slug) WHERE deleted_at IS NULL;