CREATE TABLE favourites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,

    like_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,

    CONSTRAINT fk_favourite_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_favourite_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id)
);

CREATE UNIQUE INDEX idx_favourite_user_recipe ON favourites (user_id, recipe_id) WHERE deleted_at IS NULL;

ALTER TABLE recipes
ADD COLUMN favourite_count INTEGER DEFAULT 0 NOT NULL;

UPDATE recipes r SET favourite_count = (
    SELECT COUNT(*) FROM favourites f
    WHERE f.recipe_id = r.id
);