spring.application.name=Digital Cookbook API

# H2 db
spring.datasource.url=jdbc:postgresql://localhost:5432/cookbookdb
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Naming strategy (camelCase -> snake_case)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Page defaults
spring.data.web.pageable.default-page-size=24
spring.data.web.pageable.max-page-size=48

# SQL Settings
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true